// Chain configurations for all supported networks

export const CHAINS = {
  polkadot: {
    id: 'polkadot',
    name: 'Polkadot',
    shortName: 'DOT',
    type: 'substrate',
    rpc: 'wss://rpc.polkadot.io',
    ss58Prefix: 0,
    decimals: 10,
    symbol: 'DOT',
    color: '#E6007A',
    logo: '🔴',
    coingeckoId: 'polkadot',
    subscanSlug: 'polkadot',
  },
  assetHub: {
    id: 'assetHub',
    name: 'Asset Hub',
    shortName: 'AH',
    type: 'substrate',
    rpc: 'wss://polkadot-asset-hub-rpc.polkadot.io',
    ss58Prefix: 0,
    decimals: 10,
    symbol: 'DOT',
    color: '#E6007A',
    logo: '🏦',
    coingeckoId: 'polkadot',
    subscanSlug: 'assethub-polkadot',
    assets: [
      { id: 1984, symbol: 'USDT', name: 'Tether USD',  decimals: 6,  coingeckoId: 'tether'   },
      { id: 1337, symbol: 'USDC', name: 'USD Coin',    decimals: 6,  coingeckoId: 'usd-coin' },
      { id: 17,   symbol: 'PINK', name: 'PINK Token',  decimals: 10, coingeckoId: null        },
    ],
  },
  kusama: {
    id: 'kusama',
    name: 'Kusama',
    shortName: 'KSM',
    type: 'substrate',
    rpc: 'wss://kusama-rpc.polkadot.io',
    ss58Prefix: 2,
    decimals: 12,
    symbol: 'KSM',
    color: '#000000',
    logo: '⚫',
    coingeckoId: 'kusama',
    subscanSlug: 'kusama',
  },
  moonbeam: {
    id: 'moonbeam',
    name: 'Moonbeam',
    shortName: 'GLMR',
    type: 'evm',
    rpc: 'wss://wss.api.moonbeam.network',
    evmRpc: 'https://rpc.api.moonbeam.network',
    chainId: 1284,
    ss58Prefix: 1284,
    decimals: 18,
    symbol: 'GLMR',
    color: '#53CBC8',
    logo: '🌙',
    coingeckoId: 'moonbeam',
    subscanSlug: 'moonbeam',
    erc20Tokens: [
      { address: '0x818ec0A7Fe18Ff94269904fCED6AE3DaE6d6dC0e', symbol: 'USDC', decimals: 6,  coingeckoId: 'usd-coin' },
      { address: '0xeFAeeE334F0Fd1712f9a8cc375f427D9Cdd40d73', symbol: 'USDT', decimals: 6,  coingeckoId: 'tether'   },
    ],
  },
  astar: {
    id: 'astar',
    name: 'Astar',
    shortName: 'ASTR',
    type: 'evm',
    rpc: 'wss://rpc.astar.network',
    evmRpc: 'https://evm.astar.network',
    chainId: 592,
    ss58Prefix: 5,
    decimals: 18,
    symbol: 'ASTR',
    color: '#00B4FF',
    logo: '⭐',
    coingeckoId: 'astar',
    subscanSlug: 'astar',
    erc20Tokens: [
      { address: '0x6De33698e9e9b787e09d3Bd7771ef63557E148bb', symbol: 'USDC', decimals: 6, coingeckoId: 'usd-coin' },
      { address: '0x3795C36e7D12A8c252A20C5a7B455f7c57b60283', symbol: 'USDT', decimals: 6, coingeckoId: 'tether'   },
    ],
  },
  acala: {
    id: 'acala',
    name: 'Acala',
    shortName: 'ACA',
    type: 'substrate',
    rpc: 'wss://acala-rpc.dwellir.com',
    ss58Prefix: 10,
    decimals: 12,
    symbol: 'ACA',
    color: '#E40C5B',
    logo: '🔥',
    coingeckoId: 'acala',
    subscanSlug: 'acala',
  },
  hydration: {
    id: 'hydration',
    name: 'Hydration',
    shortName: 'HDX',
    type: 'substrate',
    rpc: 'wss://hydradx-rpc.dwellir.com',
    ss58Prefix: 63,
    decimals: 12,
    symbol: 'HDX',
    color: '#4B53FF',
    logo: '💧',
    coingeckoId: 'hydradx',
    subscanSlug: 'hydration',
  },
  phala: {
    id: 'phala',
    name: 'Phala',
    shortName: 'PHA',
    type: 'substrate',
    rpc: 'wss://api.phala.network/ws',
    ss58Prefix: 30,
    decimals: 12,
    symbol: 'PHA',
    color: '#03AC58',
    logo: '🛡',
    coingeckoId: 'pha',
    subscanSlug: 'phala',
  },
  bifrost: {
    id: 'bifrost',
    name: 'Bifrost',
    shortName: 'BNC',
    type: 'substrate',
    rpc: 'wss://bifrost-rpc.dwellir.com',
    ss58Prefix: 6,
    decimals: 12,
    symbol: 'BNC',
    color: '#5B5B5B',
    logo: '🌿',
    coingeckoId: 'bifrost-native-coin',
    subscanSlug: 'bifrost',
  },
};

export const CHAIN_LIST = Object.values(CHAINS);

export const COINGECKO_IDS = [
  'polkadot',
  'kusama',
  'moonbeam',
  'astar',
  'acala',
  'hydradx',
  'pha',
  'bifrost-native-coin',
  'tether',
  'usd-coin',
];

export const DEMO_ADDRESS = '13RDY9nrJpyTDBSUdBw12dGwhk19sGwsrVZ2bxkzYHBSagP2';
